### ISSUE TITLE
FPM not found or broken?

### ISSUE THREAD

**Issue by weakcamel** [Kong/docker-fpm#90]
Hello,

Maybe I'm using it wrong but the latest image seems to be broken:

```
$ docker run -it kong/fpm:0.8.1
+ /usr/local/bin/fpm
/bin/bash: line 1: /usr/local/bin/fpm: No such file or directory
```

```
$ docker run --entrypoint bash -it kong/fpm:0.8.1
root@908b9f6b3448:/src# fpm
/usr/local/bundle/gems/fpm-1.15.0/lib/fpm/command.rb:301:in `execute': undefined method `exists?' for File:Class (NoMethodError)

    if !File.exists?(workdir)
            ^^^^^^^^
Did you mean?  exist?
	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	from /usr/local/bundle/gems/fpm-1.15.0/lib/fpm/command.rb:591:in `run'
	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from /usr/local/bundle/gems/fpm-1.15.0/bin/fpm:7:in `<top (required)>'
	from /usr/local/bundle/bin/fpm:25:in `load'
	from /usr/local/bundle/bin/fpm:25:in `<main>'
root@908b9f6b3448:/src#
root@908b9f6b3448:/src# fpm --workdir .
/usr/local/bundle/gems/fpm-1.15.0/lib/fpm/command.rb:301:in `execute': undefined method `exists?' for File:Class (NoMethodError)

    if !File.exists?(workdir)
            ^^^^^^^^
Did you mean?  exist?
	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	from /usr/local/bundle/gems/fpm-1.15.0/lib/fpm/command.rb:591:in `run'
	from /usr/local/bundle/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from /usr/local/bundle/gems/fpm-1.15.0/bin/fpm:7:in `<top (required)>'
	from /usr/local/bundle/bin/fpm:25:in `load'
	from /usr/local/bundle/bin/fpm:25:in `<main>'
root@908b9f6b3448:/src#
```

**Comment by benformosa** [comment]
This seems to be fixed in [fpm v1.15.1](https://github.com/jordansissel/fpm/releases/tag/v1.15.1)
